/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'marco' at '2/21/16 11:36 AM' with Gradle 2.8
 *
 * @author marco, @date 2/21/16 11:36 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
